import { useEffect, useRef, useState } from "react";
import { fetchAudit, fetchAuditJob, recordAuditGap, submitAudit } from "../api";
import type { AuditFinding, AuditSnapshot, ReviewJob } from "../types";

export function AuditPanel({ system, investigate }: { system: string; investigate: (query: string) => void }) {
  const [audit, setAudit] = useState<AuditSnapshot | null>(null); const [job, setJob] = useState<ReviewJob | null>(null);
  const [selected, setSelected] = useState<AuditFinding | null>(null); const [scope, setScope] = useState(""); const [locations, setLocations] = useState(""); const [action, setAction] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const poll = useRef<number | undefined>(undefined);
  useEffect(() => { fetchAudit(system).then(setAudit).catch(error => setError(error.message)); return () => window.clearInterval(poll.current); }, [system]);
  async function run() { try { const result = await submitAudit(system); setJob(result.job); poll.current = window.setInterval(async () => { const current = await fetchAuditJob(system, result.job.id); setJob(current.job); if (current.outcome.snapshot) setAudit(current.outcome.snapshot); if (["succeeded", "failed", "cancelled", "interrupted"].includes(current.job.state)) window.clearInterval(poll.current); }, 1500); } catch (error) { setError((error as Error).message); } }
  async function saveGap() { if (!selected) return; try { const result = await recordAuditGap(system, { finding_id: selected.id, section: selected.section, disposition: selected.disposition === "ANSWERED" ? "OPEN" : selected.disposition, scope, searched_locations: locations, recommended_action: action }); setMessage(`Gap recorded: ${result.path}`); setSelected(null); } catch (error) { setError((error as Error).message); } }
  return <section className="decision-desk audit-desk" aria-label="Assessment audit and gaps"><header><div><h2>Requirement and evidence audit</h2><p>Decide whether each requirement is answered, partly supported, conflicting, not found, or needs new discovery.</p></div><button onClick={run} disabled={job?.state === "running" || job?.state === "queued"}>{audit?.state === "ready" ? "Run a new audit" : "Start audit"}</button></header>{error && <p className="desk-error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}{audit?.state === "not_started" ? <p>No audit exists yet. Starting one runs framework checks without editing the assessment.</p> : <div className="audit-ledger">{audit?.findings.map(finding => <article key={finding.id}><div className="evidence-thread"><i /><span>{finding.disposition}</span></div><div><strong>{finding.section || "Document"} · {finding.requirement || finding.id}</strong><p>{finding.claim}</p><small>{finding.action}</small></div><div className="audit-actions"><button onClick={() => investigate([finding.requirement, finding.claim].filter(Boolean).join(" "))}>Search evidence</button><button className="quiet" onClick={() => { setSelected(finding); setScope(finding.section); setAction(finding.action); }}>Record gap</button></div></article>)}</div>}{audit?.state === "ready" && !audit.findings.length && <p>No open scripted findings were reported.</p>}{selected && <div className="gap-sheet"><header><h3>Record {selected.disposition.toLowerCase().replaceAll("_", " ")}</h3><button onClick={() => setSelected(null)}>×</button></header><p>This records the evidence limit. It does not prove that the capability does not exist.</p><label>Scope<input value={scope} onChange={event => setScope(event.target.value)} /></label><label>Locations searched<textarea value={locations} onChange={event => setLocations(event.target.value)} /></label><label>Recommended collection action<textarea value={action} onChange={event => setAction(event.target.value)} /></label><button disabled={!scope.trim() || !locations.trim() || !action.trim()} onClick={saveGap}>Confirm gap record</button></div>}</section>;
}
