import { useEffect, useRef, useState } from "react";
import { fetchBuildJob, fetchBuildSetup, submitBuild } from "../api";
import type { BuildOutcome, BuildSetup, ReviewJob } from "../types";

export function BuildPanel({ system }: { system: string }) {
  const [setup, setSetup] = useState<BuildSetup | null>(null); const [job, setJob] = useState<ReviewJob | null>(null);
  const [outcome, setOutcome] = useState<BuildOutcome | null>(null); const [error, setError] = useState("");
  const poll = useRef<number | undefined>(undefined);
  useEffect(() => { fetchBuildSetup(system).then(setSetup).catch(error => setError(error.message)); return () => window.clearInterval(poll.current); }, [system]);
  async function start(preview: boolean) { try { const result = await submitBuild(system, preview); setJob(result.job); setOutcome(null); poll.current = window.setInterval(async () => { const current = await fetchBuildJob(system, result.job.id); setJob(current.job); setOutcome(current.outcome); if (["succeeded", "failed", "cancelled", "interrupted"].includes(current.job.state)) window.clearInterval(poll.current); }, 1500); } catch (error) { setError((error as Error).message); } }
  if (!setup && !error) return <section className="decision-desk"><p>Reading build-lane readiness…</p></section>;
  return <section className="decision-desk build-bench" aria-label="Assessment build bench"><header><div><h2>Assessment assembly bench</h2><p>Build-lane sources become a new assessment only after every registered section and template gate passes.</p></div><span>Build lane</span></header>{error && <p className="desk-error" role="alert">{error}</p>}{setup && <><dl className="bench-identity"><div><dt>Template</dt><dd>{setup.template || "Not registered"}</dd></div><div><dt>Output</dt><dd>{setup.output || "Not registered"}</dd></div></dl><ol className="gate-ledger">{setup.gates.map(gate => <li className={gate.satisfied ? "pass" : "block"} key={gate.key}><i /> <b>{gate.key.replaceAll("_", " ")}</b><span>{gate.detail}</span></li>)}</ol><table className="bench-sections"><thead><tr><th>Section</th><th>Source</th><th>Decision</th></tr></thead><tbody>{setup.sections.map(section => <tr key={section.stable_key}><td>{section.number} {section.heading}</td><td>{section.file || "Missing"}</td><td>{section.valid ? "Ready" : "Resolve validation"}</td></tr>)}</tbody></table><footer><button disabled={!setup.ready_for_preview || Boolean(job && !outcome)} onClick={() => start(true)}>Render candidate preview</button><button disabled={!setup.ready_for_build || Boolean(job && !outcome)} onClick={() => confirm("Generate the registered assessment document? The framework will retain its manifest and backup records.") && start(false)}>Build assessment</button>{job && <span>{job.state}</span>}</footer>{outcome && <div className="build-result" role="status"><strong>{outcome.preview ? "Candidate preview" : "Generated assessment"}: {outcome.state}</strong><span>{outcome.document || "No output path reported"}</span>{outcome.document_hash && <code>{outcome.document_hash}</code>}</div>}</> }</section>;
}
